version: "3.3"
services:

  local-ipfs0:
    build: .
    container_name: local-ipfs0
    ports:
      - "4001:4001" # ipfs swarm
      - "5001:5001" # ipfs API
      - "8080:8080" # ipfs gateway
    volumes:
      - ./data/local-ipfs0:/data/ipfs
