services:

  # cluster peer0
  ipfs0:
    container_name: ipfs0
    image: ipfs/go-ipfs:release
    ports:
      - "4001:4001" # ipfs swarm
      - "5001:5001" # ipfs API
      - "8080:8080" # ipfs gateway
    volumes:
      - ./data/local-ipfs0:/data/ipfs
