#!/bin/sh
set -e
repo="$IPFS_PATH"

ipfs version

if [ -e "$repo/config" ]; then
  echo "Found IPFS fs-repo at $repo"
else
  case "$IPFS_PROFILE" in
    "") INIT_ARGS="" ;;
    *) INIT_ARGS="--profile=$IPFS_PROFILE" ;;
  esac
  ipfs init $INIT_ARGS
  ipfs config Addresses.API /ip4/0.0.0.0/tcp/5001
  ipfs config Addresses.Gateway /ip4/0.0.0.0/tcp/8080
  if [ ! -z "$AWS_ACCESS_KEY_ID" ] ; then
    echo Config s3 Datastore
    ipfs config Datastore --json "
{
  \"StorageMax\": \"1000GB\",
  \"StorageGCWatermark\": 90,
  \"GCPeriod\": \"1h\",
  \"Spec\": {
    \"mounts\": [
      {
	\"child\": {
	  \"type\": \"s3ds\",
	  \"region\": \"us-east-1\",
	  \"bucket\": \"$AWS_BUCKET_NAME\",
	  \"rootDirectory\": \"\",
	  \"accessKey\": \"$AWS_ACCESS_KEY_ID\",
	  \"secretKey\": \"$AWS_SECRET_ACCESS_KEY\"
	},
	\"mountpoint\": \"/blocks\",
	\"prefix\": \"s3.datastore\",
	\"type\": \"measure\"
      },
      {
	\"child\": {
	  \"compression\": \"none\",
	  \"path\": \"datastore\",
	  \"type\": \"levelds\"
    },
	\"mountpoint\": \"/\",
	\"prefix\": \"leveldb.datastore\",
	\"type\": \"measure\"
      }
    ],
    \"type\": \"mount\"
  },
  \"HashOnRead\": false,
  \"BloomFilterSize\": 0
}
"
  echo "{\"mounts\":[{\"bucket\":\"$AWS_BUCKET_NAME\",\"mountpoint\":\"/blocks\",\"region\":\"us-east-1\",\"rootDirectory\":\"\"},{\"mountpoint\":\"/\",\"path\":\"datastore\",\"type\":\"levelds\"}],\"type\":\"mount\"}" > $repo/datastore_spec

  fi
fi


exec ipfs "$@"
